<?php

namespace App\Helpers\Actions;

class AuthActions
{
    public const AUTHENTICATED_AS_GUEST = 'AUTHENTICATED_AS_GUEST';
    public const AUTHENTICATED_AS_USER = 'AUTHENTICATED_AS_USER';

    public const FAILED_TO_STORE_USER_DEVICE = 'FAILED_TO_STORE_USER_DEVICE';
    public const FAILED_TO_CREATE_GUEST_ACCOUNT = 'FAILED_TO_CREATE_GUEST_ACCOUNT';


    public const ATTEMPTED_TO_REGISTER_WHILE_LOGGED_IN = 'ATTEMPTED_TO_REGISTER_WHILE_LOGGED_IN';

    public const REGISTERED = 'REGISTERED';
    public const FAILED_TO_REGISTER = 'FAILED_TO_REGISTER';

    public const REGISTERED_WITH_GITHUB = 'REGISTERED_WITH_GITHUB';
    public const FAILED_TO_REGISTER_WITH_GITHUB = 'FAILED_TO_REGISTER_WITH_GITHUB';

    public const REGISTERED_WITH_FACEBOOK = 'REGISTERED_WITH_FACEBOOK';
    public const FAILED_TO_REGISTER_WITH_FACEBOOK = 'FAILED_TO_REGISTER_WITH_FACEBOOK';

    public const REGISTERED_WITH_GOOGLE = 'REGISTERED_WITH_GOOGLE';
    public const FAILED_TO_REGISTER_WITH_GOOGLE = 'FAILED_TO_REGISTER_WITH_GOOGLE';

    public const REGISTERED_WITH_LINKEDIN = 'REGISTERED_WITH_LINKEDIN';
    public const FAILED_TO_REGISTER_WITH_LINKEDIN = 'FAILED_TO_REGISTER_WITH_LINKEDIN';

    public const REGISTERED_WITH_TWITTER = 'REGISTERED_WITH_TWITTER';
    public const FAILED_TO_REGISTER_WITH_TWITTER = 'FAILED_TO_REGISTER_WITH_TWITTER';

    public const REQUESTED_RESENDING_CONFIRMATION_EMAIL = 'REQUESTED_RESENDING_CONFIRMATION_EMAIL' ;
    public const REQUESTED_RESENDING_CONFIRMATION_EMAIL_FOR_UNEXISTING_EMAIL = 'REQUESTED_RESENDING_CONFIRMATION_EMAIL_FOR_UNEXISTING_EMAIL' ;
    public const CONFIRMED_EMAIL = 'CONFIRMED_EMAIL';

    public const REQUESTED_PASSWORD_RECOVERY_EMAIL = 'REQUESTED_PASSWORD_RECOVERY_EMAIL';
    public const REQUESTED_PASSWORD_RECOVERY_EMAIL_FOR_UNEXISTING_EMAIL = 'REQUESTED_PASSWORD_RECOVERY_EMAIL_FOR_UNEXISTING_EMAIL';
    public const CONFIRMED_EMAIL_THROUGH_PASSWORD_RECOVERY = 'CONFIRMED_EMAIL_THROUGH_PASSWORD_RECOVERY';
    public const FAILED_TO_CONFIRM_EMAIL_THROUGH_PASSWORD_RECOVERY = 'FAILED_TO_CONFIRM_EMAIL_THROUGH_PASSWORD_RECOVERY';
    public const CHANGED_PASSWORD = 'CHANGED_PASSWORD';
    public const USER_ALREADY_HAS_PASSWORD_RECOVERY_TOKEN = 'USER_ALREADY_HAS_PASSWORD_RECOVERY_TOKEN';

    public const ATTEMPTED_TO_LOGIN = 'ATTEMPTED_TO_LOGIN';
    public const ATTEMPTED_TO_LOGIN_WITH_WRONG_PASSWORD = 'ATTEMPTED_TO_LOGIN_WITH_WRONG_PASSWORD';
    public const ATTEMPTED_TO_LOGIN_WITH_UNEXISTING_EMAIL = 'ATTEMPTED_TO_LOGIN_WITH_UNEXISTING_EMAIL';
    public const ATTEMPTED_TO_LOGIN_WITH_UNVERIFIED_EMAIL = 'ATTEMPTED_TO_LOGIN_WITH_UNVERIFIED_EMAIL';
    public const ATTEMPTED_TO_LOGIN_WHILE_LOGGED_IN = 'ATTEMPTED_TO_LOGIN_WHILE_LOGGED_IN';

    public const ATTEMPTED_TO_LOGIN_WITH_GITHUB = 'ATTEMPTED_TO_LOGIN_WITH_GITHUB';
    public const ATTEMPTED_TO_LOGIN_WITH_FACEBOOK = 'ATTEMPTED_TO_LOGIN_WITH_FACEBOOK';
    public const ATTEMPTED_TO_LOGIN_WITH_GOOGLE = 'ATTEMPTED_TO_LOGIN_WITH_GOOGLE';
    public const ATTEMPTED_TO_LOGIN_WITH_LINKEDIN = 'ATTEMPTED_TO_LOGIN_WITH_LINKEDIN';
    public const ATTEMPTED_TO_LOGIN_WITH_TWITTER = 'ATTEMPTED_TO_LOGIN_WITH_TWITTER';

    public const LOGGED_IN = 'LOGGED_IN';

    public const LOGGED_IN_WITH_GITHUB = 'LOGGED_IN_WITH_GITHUB';
    public const FAILED_TO_LOGIN_WITH_GITHUB = 'FAILED_TO_LOGIN_WITH_GITHUB';

    public const LOGGED_IN_WITH_FACEBOOK = 'LOGGED_IN_WITH_FACEBOOK';
    public const FAILED_TO_LOGIN_WITH_FACEBOOK = 'FAILED_TO_LOGIN_WITH_FACEBOOK';

    public const LOGGED_IN_WITH_GOOGLE = 'LOGGED_IN_WITH_GOOGLE';
    public const FAILED_TO_LOGIN_WITH_GOOGLE = 'FAILED_TO_LOGIN_WITH_GOOGLE';

    public const LOGGED_IN_WITH_LINKEDIN = 'LOGGED_IN_WITH_LINKEDIN';
    public const FAILED_TO_LOGIN_WITH_LINKEDIN = 'FAILED_TO_LOGIN_WITH_LINKEDIN';

    public const LOGGED_IN_WITH_TWITTER = 'LOGGED_IN_WITH_TWITTER';
    public const FAILED_TO_LOGIN_WITH_TWITTER = 'FAILED_TO_LOGIN_WITH_TWITTER';

    public const ATTEMPTED_TO_LOG_OUT_WITHOUT_BEING_LOGGED_IN = 'ATTEMPTED_TO_LOG_OUT_WITHOUT_BEING_LOGGED_IN';

    public const LOGGED_OUT = 'LOGGED_OUT';

    public const SAVED_DETECTED_DEVICES_AS_GUEST_TO_ACCOUNT = 'SAVED_DETECTED_DEVICES_AS_GUEST_TO_ACCOUNT';
    public const FAILED_TO_SAVE_DETECTED_DEVICES_AS_GUEST_TO_ACCOUNT = 'FAILED_TO_SAVE_DETECTED_DEVICES_AS_GUEST_TO_ACCOUNT';
    public const IMPORTED_DETECTED_DEVICES_FROM_GUEST_ACCOUNT = 'IMPORTED_DETECTED_DEVICES_FROM_GUEST_ACCOUNT';
    public const FAILED_TO_IMPORT_DETECTED_DEVICES_FROM_GUEST_ACCOUNT = 'FAILED_TO_IMPORT_DETECTED_DEVICES_FROM_GUEST_ACCOUNT';

    public const FAILED_RETRIEVING_DATA_FROM_EXISTING_AUTH_COOKIE = 'FAILED_RETRIEVING_DATA_FROM_EXISTING_AUTH_COOKIE';

    public const SAVED_ACTIONS_FROM_GUEST_TO_ACCOUNT = 'SAVED_ACTIONS_FROM_GUEST_TO_ACCOUNT';
    public const IMPORTED_ACTIONS_FROM_GUEST_ACCOUNT = 'IMPORTED_ACTIONS_FROM_GUEST_ACCOUNT';

    public const FAILED_TO_SAVE_ACTIONS_FROM_GUEST_TO_ACCOUNT = 'FAILED_TO_SAVE_ACTIONS_FROM_GUEST_TO_ACCOUNT';
    public const FAILED_TO_IMPORT_ACTIONS_FROM_GUEST_ACCOUNT = 'FAILED_TO_IMPORT_ACTIONS_FROM_GUEST_ACCOUNT';
}
