<?php

namespace App\Helpers\Actions;

class HomeControllerActions
{
    public const OPENED_HOME_PAGE_DIRECTLY = 'OPENED_HOME_PAGE_DIRECTLY';
    public const OPENED_LOGIN_PAGE_DIRECTLY = 'OPENED_LOGIN_PAGE_DIRECTLY';
    public const OPENED_REGISTER_PAGE_DIRECTLY = 'OPENED_REGISTER_PAGE_DIRECTLY';
    public const OPENED_MY_LINKS_PAGE_DIRECTLY = 'OPENED_MY_LINKS_PAGE_DIRECTLY';
    public const OPENED_CHANGE_PASSWORD_PAGE_DIRECTLY = 'OPENED_CHANGE_PASSWORD_PAGE_DIRECTLY';

}
