<?php

namespace App\Helpers\Actions;

class ShortlinkActions
{
    public const GENERATED_SHORTLINK = 'GENERATED_SHORTLINK';
    public const SENT_SHORTLINK_TO_EMAIL = 'SENT_SHORTLINK_TO_EMAIL';

    public const VISITED_AVAILABLE_SHORTLINK = 'VISITED_AVAILABLE_SHORTLINK';
    public const ATTEMPTED_TO_REGISTER_UNAVAILABLE_SHORTLINK = 'ATTEMPTED_TO_REGISTER_UNAVAILABLE_SHORTLINK';
    public const REGISTERED_CUSTOM_AVAILABLE_SHORTLINK = 'REGISTERED_CUSTOM_AVAILABLE_SHORTLINK';

    public const VISITED_ACTIVE_SHORTLINK = 'VISITED_ACTIVE_SHORTLINK';
    public const VISITED_DELETED_SHORTLINK = 'VISITED_DELETED_SHORTLINK';
    public const VISITED_SUSPENDED_SHORTLINK = 'VISITED_SUSPENDED_SHORTLINK';

    public const VIEWED_LINKS_LIST = 'VIEWED_LINKS_LIST';
    public const EDITED_SHORTLINK_DESTINATION_URL = 'EDITED_SHORTLINK_DESTINATION_URL';
    public const DELETED_SHORTLINK = 'DELETED_SHORTLINK';

}
